//go:build ignore

package winhello

/*
#cgo CFLAGS: -I${SRCDIR}/extern/webauthnwin
#define WEBAUTHN_API_VERSION_9 9
#define WEBAUTHN_API_CURRENT_VERSION WEBAUTHN_API_VERSION_9
#define WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION 9
#include <windows.h>
#include <webauthn.h>

static const int test_version = WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_CURRENT_VERSION;
*/
import "C"

type (
	GUID                                         C.GUID
	WEBAUTHN_ASSERTION                           C.WEBAUTHN_ASSERTION
	WEBAUTHN_CREDENTIAL                          C.WEBAUTHN_CREDENTIAL
	WEBAUTHN_CREDENTIALS                         C.WEBAUTHN_CREDENTIALS
	WEBAUTHN_CREDENTIAL_EX                       C.WEBAUTHN_CREDENTIAL_EX
	WEBAUTHN_CREDENTIAL_LIST                     C.WEBAUTHN_CREDENTIAL_LIST
	WEBAUTHN_EXTENSION                           C.WEBAUTHN_EXTENSION
	WEBAUTHN_EXTENSIONS                          C.WEBAUTHN_EXTENSIONS
	WEBAUTHN_CLIENT_DATA                         C.WEBAUTHN_CLIENT_DATA
	WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS C.WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS
	WEBAUTHN_RP_ENTITY_INFORMATION               C.WEBAUTHN_RP_ENTITY_INFORMATION
	WEBAUTHN_USER_ENTITY_INFORMATION             C.WEBAUTHN_USER_ENTITY_INFORMATION
)

func int32ToBool(i int32) bool {
	return i != 0
}

func boolToInt32(b bool) int32 {
	if b {
		return 1
	}
	return 0
}
