// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs .\types_webauthn.go

package winhello

type (
	GUID	struct {
		Data1	uint32
		Data2	uint16
		Data3	uint16
		Data4	[8]uint8
	}
	WEBAUTHN_ASSERTION	struct {
		DwVersion		uint32
		CbAuthenticatorData	uint32
		PbAuthenticatorData	*uint8
		CbSignature		uint32
		PbSignature		*uint8
		Credential		WEBAUTHN_CREDENTIAL
		CbUserId		uint32
		PbUserId		*uint8
		Extensions		WEBAUTHN_EXTENSIONS
		CbCredLargeBlob		uint32
		PbCredLargeBlob		*uint8
		DwCredLargeBlobStatus	uint32
		Pad_cgo_0		[4]byte
	}
	WEBAUTHN_CREDENTIAL	struct {
		DwVersion		uint32
		CbId			uint32
		PbId			*uint8
		PwszCredentialType	*uint16
	}
	WEBAUTHN_CREDENTIALS	struct {
		CCredentials	uint32
		PCredentials	*WEBAUTHN_CREDENTIAL
	}
	WEBAUTHN_CREDENTIAL_EX	struct {
		DwVersion		uint32
		CbId			uint32
		PbId			*uint8
		PwszCredentialType	*uint16
		DwTransports		uint32
		Pad_cgo_0		[4]byte
	}
	WEBAUTHN_CREDENTIAL_LIST	struct {
		CCredentials	uint32
		PpCredentials	**WEBAUTHN_CREDENTIAL_EX
	}
	WEBAUTHN_EXTENSION	struct {
		PwszExtensionIdentifier	*uint16
		CbExtension		uint32
		PvExtension		*byte
	}
	WEBAUTHN_EXTENSIONS	struct {
		CExtensions	uint32
		PExtensions	*WEBAUTHN_EXTENSION
	}
	WEBAUTHN_CLIENT_DATA	struct {
		DwVersion		uint32
		CbClientDataJSON	uint32
		PbClientDataJSON	*uint8
		PwszHashAlgId		*uint16
	}
	WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS	struct {
		DwVersion			uint32
		DwTimeoutMilliseconds		uint32
		CredentialList			WEBAUTHN_CREDENTIALS
		Extensions			WEBAUTHN_EXTENSIONS
		DwAuthenticatorAttachment	uint32
		DwUserVerificationRequirement	uint32
		DwFlags				uint32
		PwszU2fAppId			*uint16
		PbU2fAppId			*int32
		PCancellationId			*GUID
		PAllowCredentialList		*WEBAUTHN_CREDENTIAL_LIST
		DwCredLargeBlobOperation	uint32
		CbCredLargeBlob			uint32
		PbCredLargeBlob			*uint8
	}
	WEBAUTHN_RP_ENTITY_INFORMATION	struct {
		DwVersion	uint32
		PwszId		*uint16
		PwszName	*uint16
		PwszIcon	*uint16
	}
	WEBAUTHN_USER_ENTITY_INFORMATION	struct {
		DwVersion	uint32
		CbId		uint32
		PbId		*uint8
		PwszName	*uint16
		PwszIcon	*uint16
		PwszDisplayName	*uint16
	}
)

func int32ToBool(i int32) bool {
	return i != 0
}

func boolToInt32(b bool) int32 {
	if b {
		return 1
	}
	return 0
}
